import type { LucideIcon } from "lucide-react";
import { Cookie, FileText, ShieldCheck } from "lucide-react";

export type LegalSlug = "privacy" | "terms" | "cookies";

export type LegalBlock =
  | { type: "paragraph"; text: string }
  | { type: "list"; items: string[] }
  | { type: "notice"; tone: "info" | "warning" | "success"; title: string; text: string }
  | { type: "card"; title: string; text: string; items?: string[] };

export type LegalSectionData = {
  id: string;
  title: string;
  blocks: LegalBlock[];
};

export type LegalPageData = {
  slug: LegalSlug;
  title: string;
  badge: string;
  description: string;
  lastUpdated: string;
  sections: LegalSectionData[];
};

export const legalNav: Array<{ slug: LegalSlug; title: string; href: string; icon: LucideIcon }> = [
  { slug: "privacy", title: "Privacy Policy", href: "/legal/privacy", icon: ShieldCheck },
  { slug: "terms", title: "Terms of Service", href: "/legal/terms", icon: FileText },
  { slug: "cookies", title: "Cookie Policy", href: "/legal/cookies", icon: Cookie },
];

export const siteUrl = process.env.NEXT_PUBLIC_SITE_URL || "https://auraproxy.dev";

export const legalPages: Record<LegalSlug, LegalPageData> = {
  privacy: {
    slug: "privacy",
    title: "Privacy Policy",
    badge: "Privacy",
    description:
      "How Aura Proxy collects, uses, protects, and retains information when teams route, cache, observe, and govern LLM requests through the gateway.",
    lastUpdated: "July 14, 2026",
    sections: [
      {
        id: "introduction",
        title: "Introduction",
        blocks: [
          {
            type: "paragraph",
            text:
              "This Privacy Policy explains how Aura Proxy, Inc. collects, uses, discloses, and protects information in connection with Aura Proxy, our AI gateway, dashboard, APIs, websites, and related services.",
          },
          {
            type: "paragraph",
            text:
              "Aura Proxy acts as an intermediary between customers and AI providers. We process information to deliver routing, caching, observability, policy enforcement, authentication, billing, support, and security features.",
          },
          {
            type: "notice",
            tone: "info",
            title: "Customer control",
            text:
              "Prompt and response logging is configurable by workspace administrators. Customers remain responsible for deciding what data they send through the gateway and how their workspace retention settings are configured.",
          },
        ],
      },
      {
        id: "information-we-collect",
        title: "Information We Collect",
        blocks: [
          {
            type: "paragraph",
            text:
              "We collect information that you provide directly, information generated by your use of Aura Proxy, and information from third-party services you choose to connect.",
          },
          {
            type: "list",
            items: [
              "Account details such as name, email address, organization, role, authentication identifiers, and workspace membership.",
              "Configuration data such as projects, API keys, provider connections, routing preferences, budgets, alerts, and cache settings.",
              "Usage data such as request counts, cache hits, latency, token usage, provider selection, model names, error states, and cost estimates.",
              "Technical data such as IP address, browser, device type, operating system, session identifiers, referral pages, and approximate location derived from network data.",
            ],
          },
        ],
      },
      {
        id: "account-information",
        title: "Account Information",
        blocks: [
          {
            type: "paragraph",
            text:
              "When you create an account or join a workspace, we collect information required to authenticate you, identify your workspace, provide support, and administer access controls. This may include your name, email address, password hash if credentials are used, OAuth account identifiers, session records, role, plan, and workspace settings.",
          },
          {
            type: "paragraph",
            text:
              "We use account information to operate the service, prevent unauthorized access, communicate service notices, support password reset flows, and maintain auditability for administrative actions.",
          },
        ],
      },
      {
        id: "billing-information",
        title: "Billing Information",
        blocks: [
          {
            type: "paragraph",
            text:
              "Paid plans may be billed through Stripe or another payment processor. We may receive billing identifiers, subscription status, plan details, invoices, tax information, and limited payment metadata from our billing provider.",
          },
          {
            type: "paragraph",
            text:
              "Aura Proxy does not intentionally store full payment card numbers. Payment information is processed by our payment provider under its own terms and privacy policy.",
          },
        ],
      },
      {
        id: "api-usage-data",
        title: "API Usage Data",
        blocks: [
          {
            type: "paragraph",
            text:
              "Aura Proxy records operational data about requests sent through the gateway, including project ID, API key prefix or internal identifier, provider, model, status code, token counts, latency, cache status, cost estimates, and timestamps.",
          },
          {
            type: "paragraph",
            text:
              "We use API usage data to provide dashboards, rate limiting, budget controls, alerts, abuse prevention, troubleshooting, reliability analysis, and cost reporting.",
          },
        ],
      },
      {
        id: "prompt-and-response-handling",
        title: "Prompt and Response Handling",
        blocks: [
          {
            type: "paragraph",
            text:
              "Aura Proxy may temporarily process request payloads, prompts, responses, tool calls, and related parameters to deliver routing, caching, observability, retries, policy checks, and provider interoperability.",
          },
          {
            type: "paragraph",
            text:
              "Customers retain ownership of their prompts, responses, and other content submitted through the service. We do not claim ownership of customer content, and we use it only as necessary to provide, secure, support, and improve Aura Proxy as described in this Policy and customer settings.",
          },
          {
            type: "notice",
            tone: "warning",
            title: "Sensitive content",
            text:
              "Do not send regulated, highly sensitive, or confidential information through Aura Proxy unless your workspace configuration, provider agreements, and internal policies authorize that processing.",
          },
        ],
      },
      {
        id: "request-metadata",
        title: "Request Metadata",
        blocks: [
          {
            type: "paragraph",
            text:
              "Request metadata may include headers selected for routing or observability, model parameters, provider identifiers, cache similarity scores, fallback attempts, error messages, and timing measurements.",
          },
          {
            type: "paragraph",
            text:
              "We avoid collecting more metadata than needed for product functionality, security, analytics, and support. Workspace administrators should avoid placing secrets or personal data in custom metadata fields.",
          },
        ],
      },
      {
        id: "logs",
        title: "Logs",
        blocks: [
          {
            type: "paragraph",
            text:
              "Aura Proxy maintains service logs, audit logs, request logs, and security logs. These logs help customers understand gateway behavior and help us detect errors, investigate abuse, maintain availability, and improve reliability.",
          },
          {
            type: "paragraph",
            text:
              "Prompt and response logging can be configured by workspace administrators. Depending on configuration, logs may include payload excerpts, full payloads, redacted payloads, or metadata-only records.",
          },
        ],
      },
      {
        id: "analytics",
        title: "Analytics",
        blocks: [
          {
            type: "paragraph",
            text:
              "We use analytics to understand product usage, diagnose performance issues, evaluate feature adoption, and improve the dashboard and APIs. Analytics may include aggregated usage metrics, page views, session events, and device information.",
          },
          {
            type: "paragraph",
            text:
              "We may de-identify or aggregate data so it no longer reasonably identifies a particular customer, user, or workspace, and may use that information for product, security, and business purposes.",
          },
        ],
      },
      {
        id: "cookies",
        title: "Cookies",
        blocks: [
          {
            type: "paragraph",
            text:
              "We use cookies and similar technologies for authentication, security, preferences, analytics, and performance. For more detail, review our Cookie Policy.",
          },
        ],
      },
      {
        id: "third-party-services",
        title: "Third-party Services",
        blocks: [
          {
            type: "paragraph",
            text:
              "Aura Proxy may integrate with third-party services such as authentication providers, Stripe, Vercel, Cloudflare, email providers, analytics tools, and AI providers including OpenAI, Anthropic, Google Gemini, Mistral, Groq, OpenRouter, and DeepSeek.",
          },
          {
            type: "paragraph",
            text:
              "When you connect or route requests to third-party providers, those providers may process information under their own terms, privacy policies, data processing terms, and retention settings. You are responsible for selecting providers appropriate for your use case.",
          },
        ],
      },
      {
        id: "data-security",
        title: "Data Security",
        blocks: [
          {
            type: "paragraph",
            text:
              "We implement technical and organizational measures designed to protect customer information, including access controls, encryption in transit, encryption at rest for sensitive information, credential hashing where appropriate, monitoring, and least-privilege operational practices.",
          },
          {
            type: "paragraph",
            text:
              "No system is perfectly secure. Customers should protect API keys, rotate credentials when needed, configure appropriate permissions, and notify us promptly if they suspect unauthorized access.",
          },
        ],
      },
      {
        id: "international-transfers",
        title: "International Transfers",
        blocks: [
          {
            type: "paragraph",
            text:
              "Aura Proxy and our service providers may process information in countries other than where you are located. These countries may have data protection laws that differ from those in your jurisdiction.",
          },
          {
            type: "paragraph",
            text:
              "Where required, we use appropriate safeguards designed to support lawful international transfers, such as contractual protections with service providers.",
          },
        ],
      },
      {
        id: "data-retention",
        title: "Data Retention",
        blocks: [
          {
            type: "paragraph",
            text:
              "We retain information for as long as needed to provide Aura Proxy, comply with legal obligations, resolve disputes, enforce agreements, protect the service, and support customer-configured retention settings.",
          },
          {
            type: "paragraph",
            text:
              "Request logs, cache entries, analytics records, and security logs may have different retention periods depending on workspace settings, plan features, operational needs, and legal requirements.",
          },
        ],
      },
      {
        id: "user-rights",
        title: "User Rights",
        blocks: [
          {
            type: "paragraph",
            text:
              "Depending on your location and applicable law, you may have rights to access, correct, delete, export, restrict, or object to certain processing of personal information.",
          },
          {
            type: "paragraph",
            text:
              "If your information is controlled by a customer workspace, we may direct your request to that customer or require authorization before taking action.",
          },
        ],
      },
      {
        id: "deleting-data",
        title: "Deleting Data",
        blocks: [
          {
            type: "paragraph",
            text:
              "Workspace administrators may delete projects, API keys, provider credentials, cache records, and certain logs through product controls where available. You may also contact us to request account deletion.",
          },
          {
            type: "paragraph",
            text:
              "We may retain limited information after deletion where necessary for security, billing, legal compliance, backups, dispute resolution, or enforcement of our agreements.",
          },
        ],
      },
      {
        id: "childrens-privacy",
        title: "Children's Privacy",
        blocks: [
          {
            type: "paragraph",
            text:
              "Aura Proxy is intended for business and developer use and is not directed to children under 13 or the equivalent minimum age in your jurisdiction. We do not knowingly collect personal information from children.",
          },
        ],
      },
      {
        id: "changes-to-this-policy",
        title: "Changes to this Policy",
        blocks: [
          {
            type: "paragraph",
            text:
              "We may update this Privacy Policy from time to time. If changes are material, we will provide notice through the service, by email, or by another reasonable method. The updated policy will be effective when posted unless stated otherwise.",
          },
        ],
      },
      {
        id: "contact",
        title: "Contact",
        blocks: [
          {
            type: "paragraph",
            text:
              "For privacy questions or requests, contact Aura Proxy at privacy@auraproxy.dev. Please include enough information for us to understand your request and verify your authority to act on the relevant account or workspace.",
          },
        ],
      },
    ],
  },
  terms: {
    slug: "terms",
    title: "Terms of Service",
    badge: "Terms",
    description:
      "The terms that govern access to Aura Proxy's AI gateway, dashboard, APIs, routing, caching, observability, and policy enforcement features.",
    lastUpdated: "July 14, 2026",
    sections: [
      {
        id: "acceptance-of-terms",
        title: "Acceptance of Terms",
        blocks: [
          {
            type: "paragraph",
            text:
              "These Terms of Service govern your access to and use of Aura Proxy, including our websites, dashboard, APIs, documentation, software, and related services. By creating an account, accessing the service, or using Aura Proxy, you agree to these Terms.",
          },
          {
            type: "paragraph",
            text:
              "If you use Aura Proxy on behalf of a company or other entity, you represent that you have authority to bind that entity. In that case, \"you\" and \"your\" refer to that entity.",
          },
        ],
      },
      {
        id: "eligibility",
        title: "Eligibility",
        blocks: [
          {
            type: "paragraph",
            text:
              "You must be at least 18 years old and legally able to enter into these Terms. You may not use Aura Proxy if you are barred from doing so under applicable law or if we previously suspended your account for material violation of these Terms.",
          },
        ],
      },
      {
        id: "accounts",
        title: "Accounts",
        blocks: [
          {
            type: "paragraph",
            text:
              "You are responsible for maintaining accurate account information, protecting login credentials, managing workspace access, and all activity under your account or API keys.",
          },
          {
            type: "paragraph",
            text:
              "You must promptly notify us if you suspect unauthorized access, credential compromise, or misuse of Aura Proxy.",
          },
        ],
      },
      {
        id: "api-keys",
        title: "API Keys",
        blocks: [
          {
            type: "paragraph",
            text:
              "Aura Proxy uses project-scoped API keys and provider credentials to route requests. You are responsible for securing API keys, limiting access, rotating credentials, and revoking keys that are no longer needed.",
          },
          {
            type: "notice",
            tone: "warning",
            title: "Key handling",
            text:
              "Do not expose Aura Proxy API keys or provider credentials in client-side code, public repositories, browser logs, or support tickets.",
          },
        ],
      },
      {
        id: "acceptable-use",
        title: "Acceptable Use",
        blocks: [
          {
            type: "paragraph",
            text:
              "You may use Aura Proxy to route, monitor, cache, and secure requests to supported AI providers in compliance with these Terms, our documentation, applicable law, and the terms of any third-party providers you use.",
          },
          {
            type: "paragraph",
            text:
              "You are responsible for the applications, prompts, responses, workflows, policies, and users connected to your workspace.",
          },
        ],
      },
      {
        id: "prohibited-uses",
        title: "Prohibited Uses",
        blocks: [
          {
            type: "list",
            items: [
              "Attempting to bypass authentication, rate limits, budget controls, abuse controls, or security measures.",
              "Using Aura Proxy to violate applicable law, third-party rights, sanctions, export controls, or AI provider policies.",
              "Sending malware, harmful code, phishing content, credential harvesting flows, or traffic designed to disrupt infrastructure.",
              "Reverse engineering hosted service components except where applicable law prohibits this restriction.",
              "Using the service to build or operate systems that require fail-safe performance unless you independently validate and monitor them.",
            ],
          },
        ],
      },
      {
        id: "payments",
        title: "Payments",
        blocks: [
          {
            type: "paragraph",
            text:
              "If you subscribe to a paid plan, you authorize us and our payment processor to charge applicable fees, taxes, and usage-based amounts using the payment method you provide.",
          },
          {
            type: "paragraph",
            text:
              "Fees are stated in U.S. dollars unless otherwise specified. You are responsible for taxes, duties, and charges imposed by governmental authorities, excluding taxes based on our net income.",
          },
        ],
      },
      {
        id: "billing",
        title: "Billing",
        blocks: [
          {
            type: "paragraph",
            text:
              "Billing cycles, included usage, overage fees, and renewal terms are described at checkout, in your order, or in the dashboard. Usage records in Aura Proxy may be used to calculate fees and enforce budget limits.",
          },
          {
            type: "paragraph",
            text:
              "You must keep billing information current. If payment fails, we may suspend or limit access after reasonable notice unless immediate action is needed to prevent risk to the service.",
          },
        ],
      },
      {
        id: "subscriptions",
        title: "Subscriptions",
        blocks: [
          {
            type: "paragraph",
            text:
              "Subscriptions renew automatically unless canceled before the renewal date. You can cancel future renewals through the dashboard or by contacting support where dashboard cancellation is unavailable.",
          },
          {
            type: "paragraph",
            text:
              "Downgrades or cancellations may reduce limits, disable paid features, or affect retention of logs, cache entries, and analytics after the current billing period.",
          },
        ],
      },
      {
        id: "refund-policy",
        title: "Refund Policy",
        blocks: [
          {
            type: "paragraph",
            text:
              "Except where required by law or expressly stated in an order, fees are non-refundable. We may issue credits or refunds at our discretion, but doing so does not create an obligation to provide similar credits or refunds later.",
          },
        ],
      },
      {
        id: "rate-limits",
        title: "Rate Limits",
        blocks: [
          {
            type: "paragraph",
            text:
              "Aura Proxy may apply rate limits, concurrency limits, quotas, budget controls, and abuse protections at the account, workspace, project, API key, provider, or infrastructure level.",
          },
          {
            type: "paragraph",
            text:
              "We may temporarily throttle, queue, reject, or suspend requests that exceed limits, threaten reliability, or appear abusive.",
          },
        ],
      },
      {
        id: "service-availability",
        title: "Service Availability",
        blocks: [
          {
            type: "paragraph",
            text:
              "We work to keep Aura Proxy reliable, but the service may be unavailable due to maintenance, incidents, third-party outages, provider limitations, network conditions, or events outside our control.",
          },
          {
            type: "paragraph",
            text:
              "Unless a separate written agreement provides a service level commitment, Aura Proxy is provided without a guaranteed uptime commitment.",
          },
        ],
      },
      {
        id: "third-party-providers",
        title: "Third-party Providers",
        blocks: [
          {
            type: "paragraph",
            text:
              "Aura Proxy connects to third-party AI providers and infrastructure services. We do not control those providers, their models, output quality, pricing, availability, policy enforcement, or data handling practices.",
          },
          {
            type: "paragraph",
            text:
              "You are responsible for maintaining provider accounts, accepting provider terms, configuring provider credentials, and ensuring your use of provider services is permitted.",
          },
        ],
      },
      {
        id: "intellectual-property",
        title: "Intellectual Property",
        blocks: [
          {
            type: "paragraph",
            text:
              "Aura Proxy and its software, design, documentation, trademarks, and service materials are owned by Aura Proxy, Inc. or our licensors. Subject to these Terms, we grant you a limited, non-exclusive, non-transferable right to use the service.",
          },
          {
            type: "paragraph",
            text:
              "Open-source components, if any, are licensed under their applicable open-source licenses. These Terms do not limit rights you may have under those licenses.",
          },
        ],
      },
      {
        id: "customer-data",
        title: "Customer Data",
        blocks: [
          {
            type: "paragraph",
            text:
              "You retain ownership of prompts, responses, configurations, logs, metadata, and other content you submit to Aura Proxy. You grant us the rights needed to host, process, transmit, cache, display, secure, and support Customer Data to provide the service.",
          },
          {
            type: "paragraph",
            text:
              "You represent that you have the necessary rights and permissions to submit Customer Data to Aura Proxy and to route it to the AI providers and services you configure.",
          },
        ],
      },
      {
        id: "termination",
        title: "Termination",
        blocks: [
          {
            type: "paragraph",
            text:
              "You may stop using Aura Proxy at any time. We may suspend or terminate access if you materially breach these Terms, create security or operational risk, fail to pay fees, or use the service in a way that may cause liability or harm.",
          },
          {
            type: "paragraph",
            text:
              "After termination, your right to use the service ends. We may delete or retain data in accordance with our Privacy Policy, product settings, legal obligations, and backup practices.",
          },
        ],
      },
      {
        id: "limitation-of-liability",
        title: "Limitation of Liability",
        blocks: [
          {
            type: "paragraph",
            text:
              "To the maximum extent permitted by law, Aura Proxy, Inc. and its affiliates, officers, employees, agents, suppliers, and licensors will not be liable for indirect, incidental, special, consequential, exemplary, or punitive damages, or for lost profits, revenues, data, goodwill, or business interruption.",
          },
          {
            type: "paragraph",
            text:
              "To the maximum extent permitted by law, our total liability for all claims relating to the service or these Terms will not exceed the greater of one hundred U.S. dollars or the amounts you paid to Aura Proxy for the service giving rise to the claim in the twelve months before the event giving rise to liability.",
          },
        ],
      },
      {
        id: "disclaimer",
        title: "Disclaimer",
        blocks: [
          {
            type: "paragraph",
            text:
              "Aura Proxy is provided on an \"as is\" and \"as available\" basis. To the maximum extent permitted by law, we disclaim warranties of merchantability, fitness for a particular purpose, title, non-infringement, and uninterrupted or error-free operation.",
          },
          {
            type: "paragraph",
            text:
              "We do not warrant the accuracy, safety, legality, or usefulness of AI provider outputs. You are responsible for evaluating outputs and applying appropriate human review, monitoring, and safeguards.",
          },
        ],
      },
      {
        id: "indemnification",
        title: "Indemnification",
        blocks: [
          {
            type: "paragraph",
            text:
              "You will defend, indemnify, and hold harmless Aura Proxy, Inc. and its affiliates, officers, employees, agents, suppliers, and licensors from claims, damages, liabilities, losses, and expenses arising from your Customer Data, your use of the service, your applications, your violation of these Terms, or your violation of law or third-party rights.",
          },
        ],
      },
      {
        id: "changes",
        title: "Changes",
        blocks: [
          {
            type: "paragraph",
            text:
              "We may update these Terms from time to time. If changes are material, we will provide reasonable notice. Continued use of Aura Proxy after updated Terms become effective means you accept the updated Terms.",
          },
        ],
      },
      {
        id: "governing-law",
        title: "Governing Law",
        blocks: [
          {
            type: "paragraph",
            text:
              "These Terms are governed by the laws of the State of Delaware and the federal laws of the United States, without regard to conflict of law principles. Courts located in Delaware will have exclusive jurisdiction for disputes not subject to a separate written dispute resolution agreement.",
          },
        ],
      },
      {
        id: "contact",
        title: "Contact",
        blocks: [
          {
            type: "paragraph",
            text:
              "For questions about these Terms, contact Aura Proxy at legal@auraproxy.dev. Please include your workspace name and the email address associated with your account when relevant.",
          },
        ],
      },
    ],
  },
  cookies: {
    slug: "cookies",
    title: "Cookie Policy",
    badge: "Cookies",
    description:
      "How Aura Proxy uses cookies and similar technologies for authentication, security, preferences, analytics, and performance.",
    lastUpdated: "July 14, 2026",
    sections: [
      {
        id: "introduction",
        title: "Introduction",
        blocks: [
          {
            type: "paragraph",
            text:
              "This Cookie Policy explains how Aura Proxy uses cookies and similar technologies when you visit our websites, sign in to the dashboard, use our APIs, or interact with related services.",
          },
          {
            type: "paragraph",
            text:
              "Cookies help us authenticate users, secure workspaces, remember preferences, analyze usage, and keep the service reliable.",
          },
        ],
      },
      {
        id: "what-cookies-are",
        title: "What Cookies Are",
        blocks: [
          {
            type: "paragraph",
            text:
              "Cookies are small text files placed on your device by a website or application. Similar technologies include local storage, pixels, SDKs, and server-side identifiers that support authentication, analytics, security, and performance measurement.",
          },
        ],
      },
      {
        id: "why-we-use-cookies",
        title: "Why We Use Cookies",
        blocks: [
          {
            type: "list",
            items: [
              "To keep you signed in and route you to the correct workspace.",
              "To protect accounts, sessions, forms, and API management flows.",
              "To remember interface preferences and reduce repetitive setup.",
              "To understand product usage, diagnose errors, and improve performance.",
              "To measure the effectiveness of pages, documentation, and onboarding flows.",
            ],
          },
        ],
      },
      {
        id: "essential-cookies",
        title: "Essential Cookies",
        blocks: [
          {
            type: "paragraph",
            text:
              "Essential cookies are required for core service functions such as navigation, session management, account access, workspace selection, CSRF protection, and load balancing.",
          },
          {
            type: "notice",
            tone: "info",
            title: "Required operation",
            text:
              "Because essential cookies are necessary for Aura Proxy to work, they cannot be disabled through our cookie controls.",
          },
        ],
      },
      {
        id: "authentication-cookies",
        title: "Authentication Cookies",
        blocks: [
          {
            type: "paragraph",
            text:
              "Authentication cookies help verify your identity, maintain sessions, remember login state, and support secure sign-in through credential or third-party authentication providers.",
          },
        ],
      },
      {
        id: "security-cookies",
        title: "Security Cookies",
        blocks: [
          {
            type: "paragraph",
            text:
              "Security cookies and similar identifiers help detect suspicious behavior, protect forms, prevent cross-site request forgery, enforce rate limits, and reduce the risk of unauthorized access.",
          },
        ],
      },
      {
        id: "analytics-cookies",
        title: "Analytics Cookies",
        blocks: [
          {
            type: "paragraph",
            text:
              "Analytics cookies help us understand how visitors and customers use Aura Proxy, including which pages are visited, which flows are completed, where errors occur, and which features need improvement.",
          },
          {
            type: "paragraph",
            text:
              "Where required, we will request consent before using non-essential analytics cookies.",
          },
        ],
      },
      {
        id: "preference-cookies",
        title: "Preference Cookies",
        blocks: [
          {
            type: "paragraph",
            text:
              "Preference cookies remember settings such as selected workspace, dismissed notices, display preferences, and other interface choices that make repeated use of the dashboard smoother.",
          },
        ],
      },
      {
        id: "performance-cookies",
        title: "Performance Cookies",
        blocks: [
          {
            type: "paragraph",
            text:
              "Performance cookies and related signals help us measure page load time, application responsiveness, failed requests, and reliability across browser, edge, and hosting infrastructure.",
          },
        ],
      },
      {
        id: "third-party-cookies",
        title: "Third-party Cookies",
        blocks: [
          {
            type: "paragraph",
            text:
              "Third-party services such as authentication providers, Stripe, Vercel, Cloudflare, support tools, and analytics providers may set cookies or similar technologies when they provide services to Aura Proxy.",
          },
          {
            type: "paragraph",
            text:
              "These third parties process information under their own policies. Their cookies may be necessary for payment processing, hosting, security, analytics, or authentication features.",
          },
        ],
      },
      {
        id: "managing-cookies",
        title: "Managing Cookies",
        blocks: [
          {
            type: "paragraph",
            text:
              "You can manage non-essential cookies through available consent controls, browser settings, and device settings. Disabling some cookies may affect dashboard functionality, authentication, analytics accuracy, or preference persistence.",
          },
        ],
      },
      {
        id: "browser-controls",
        title: "Browser Controls",
        blocks: [
          {
            type: "paragraph",
            text:
              "Most browsers allow you to block, delete, or limit cookies. Browser controls vary, so review your browser documentation for details. If you block all cookies, you may not be able to sign in or use core Aura Proxy features.",
          },
        ],
      },
      {
        id: "do-not-track",
        title: "Do Not Track",
        blocks: [
          {
            type: "paragraph",
            text:
              "Some browsers offer Do Not Track signals. Because there is no consistent industry standard for responding to these signals, Aura Proxy does not currently respond to them. We will update this policy if a standard approach becomes available.",
          },
        ],
      },
      {
        id: "changes",
        title: "Changes",
        blocks: [
          {
            type: "paragraph",
            text:
              "We may update this Cookie Policy as our practices, technologies, or legal requirements change. The updated policy will be effective when posted unless stated otherwise.",
          },
        ],
      },
      {
        id: "contact",
        title: "Contact",
        blocks: [
          {
            type: "paragraph",
            text:
              "For questions about cookies or similar technologies, contact Aura Proxy at privacy@auraproxy.dev.",
          },
        ],
      },
    ],
  },
};
